/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.awt.*;
import java.sql.*;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.border.*;
import trouvaille_destiano.setup;
/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String encrypt(String str)
    {
        Random no=new Random();
        String message, code=" ";
        int rand;
        char ch;        
        int size=str.length();
        for (int i=0;i<=size-1;i++) {
            ch=str.charAt(i);
            int ascii=(int)ch;
            for(rand=0;rand%2==0;rand=1+no.nextInt(10)){}
            int c = (ascii-65)*rand;
            code += c + "(" + rand + ").";
        }
        return code;
    }
    public static String decrypt(String str)
    {
        String m="";
        char c;
        int size=str.length();
        for (int i=0;i<=size-1;i++){
            String ncod="",rcod="";
            for(c=str.charAt(i++);c!='(';c=str.charAt(i++))
                ncod += c;
            for(c=str.charAt(i++);c!=')';c=str.charAt(i++))
                rcod += c;
            int nc=Integer.parseInt(ncod);
            int rc=Integer.parseInt(rcod);
            int cod = (nc/rc)+65;
            m+=(char)cod;            
        }
       return m;        
    }
    public Login() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        System.out.println(decrypt("-112(7).-16(1).-80(5)."));
       
        final int s=60;
        Thread th=new Thread(){
               public void run(){
                    try{ 
                        for(int t=1;t<=3;t++){
                            jLabel9.setText("");
                            if(t==1){
                                String m1="Let's find some beautiful place to get lost..";
                                for(int i=0;i<m1.length();i++){
                                    Thread.sleep(s);
                                    jLabel9.setText(jLabel9.getText()+m1.charAt(i));
                                }
                                Thread.sleep(1000);
                                for(int i=0;i<m1.length();i++){
                                     jLabel9.setText("");
                                        jLabel9.setText(m1.substring(0, (m1.length()-i)));
                                        Thread.sleep(s);                          
                                }
                            }
                            
                            if(t==2){
                                String m1="Go where you feel most Alive..";
                                for(int i=0;i<m1.length();i++){
                                    Thread.sleep(s);
                                    jLabel9.setText(jLabel9.getText()+m1.charAt(i));
                                }
                                Thread.sleep(1000);
                                for(int i=0;i<m1.length();i++){
                                     jLabel9.setText("");
                                        jLabel9.setText(m1.substring(0, (m1.length()-i)));
                                        Thread.sleep(s);                         
                                }
                            }
                            if(t==3){
                                String m1="Let us find the best route for you!";
                                for(int i=0;i<m1.length();i++){
                                    Thread.sleep(s);
                                    jLabel9.setText(jLabel9.getText()+m1.charAt(i));
                                }
                                Thread.sleep(1000);
                                for(int i=0;i<m1.length();i++){
                                     jLabel9.setText("");
                                        jLabel9.setText(m1.substring(0, (m1.length()-i)));
                                        Thread.sleep(s);           
                                }
                                t-=3;
                            }
                            
                        
                        }
                    }catch(Exception e){}
                    }
            };th.start();
            //i++;
        
    }
    int a=0,b=0,o=0;
    int port = 3306;
    //int s=60;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new RoundedPanel(150, Color.white);
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(0,0,0,0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("User ID");
        jLabel6.setEnabled(false);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Login");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 102, 153));
        jCheckBox1.setText("Administrator");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 102, 153));
        jCheckBox2.setText("Customer");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jLabel3.setEnabled(false);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, 40));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setMinimumSize(new java.awt.Dimension(60, 90));
        jTextField2.setPreferredSize(new java.awt.Dimension(60, 90));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 250, 40));

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 118, -1));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, 20));

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, 19));

        jButton4.setBackground(new Color(0,0,0,0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 153));
        jButton4.setText("Create new Account");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 232, -1));

        jButton3.setBackground(new Color(225,225,225));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("X");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 46, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock (1).png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon.png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(new Color(204,0,0));
        jButton3.setForeground(new Color(225,225,225));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setForeground(new Color(204,0,0));
        jButton3.setBackground(new Color(225,225,225));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSignUp().setVisible(true);
            }
        });
         this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        int t=0;
        try{
            Class.forName("java.sql.Driver");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:"+port+"/trouvaille_destiano","root","root");
            Statement stmt=cn.createStatement();
            ResultSet rs;
            if(jCheckBox2.isSelected()){
                rs=stmt.executeQuery("select * from user");
                while(rs.next()){
                    if(decrypt(rs.getString("user_id").trim()).equals(jTextField2.getText())){  
                        if(decrypt(rs.getString("password").trim()).equals(jTextField1.getText())){                                                      
                                    Home h=new Home();
                                    h.setVisible(true);
                                    this.dispose();
                                    h.jLabel4.setText(rs.getString("Name"));
                                    h.jLabel6.setText(rs.getString("p_no"));
                                    if(rs.getString("gender").equals("1"))
                                        h.jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/man.png")));
                                    else if(rs.getString("gender").equals("2"))
                                        h.jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/girl.png")));
                                    else if(rs.getString("gender").equals("0"))
                                        h.jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transgender.png")));
                                    else{}
                                    this.dispose();
                                }                            
                            else{
                                jLabel2.setText("Incorrect Password!!");
                                jLabel2.setVisible(true);                    
                            }                
                        
                    }
                    t++;
                }
                if(t>0){
                    jLabel1.setText("Incorrect User Name!!");
                    jLabel1.setVisible(true); 
                    t=0;
                }
            }
            if(jCheckBox1.isSelected()){
                rs=stmt.executeQuery("select * from admin");
                while(rs.next()){
                    if(decrypt(rs.getString("user_id").trim()).equals(jTextField2.getText())){
                        if(decrypt(rs.getString("password").trim()).equals(jTextField1.getText())){                                                      
                                    AdminHome ah=new AdminHome();
                                    ah.setVisible(true);
                                    this.dispose();
                                    ah.jLabel4.setText(rs.getString("Name"));
                                    ah.jLabel6.setText(rs.getString("p_no"));
                                    ah.jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/boss.png")));
                                    this.dispose();
                                }                            
                            else{
                                jLabel2.setText("Incorrect Password!!");
                                jLabel2.setVisible(true);                    
                            }                
                        
                    }
                    t++;
                }
                if(t>0){
                    jLabel1.setText("Incorrect User Name!!");
                    jLabel1.setVisible(true);                    
                }
            }
            }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setForeground(new Color(0,102,153));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,102,153));
        jButton1.setForeground(new Color(225,225,225));

    }//GEN-LAST:event_jButton1MouseEntered

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        if(jTextField2.getText().equals("")){
            jLabel6.setVisible(true);
        }
        else{
            jLabel6.setVisible(false);            
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
            jLabel3.setVisible(true);
        }
        else{
            jLabel3.setVisible(false);            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        jTextField2.setBorder(new CompoundBorder(new LineBorder(new Color(0,102,153), 2),new EmptyBorder(7,7,7,7)));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card (1).png")));
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        jTextField2.setBorder(new CompoundBorder(new LineBorder(new Color(0,0,0), 2),new EmptyBorder(7,7,7,7)));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card.png")));
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setBorder(new CompoundBorder(new LineBorder(new Color(0,102,150), 2),new EmptyBorder(7,7,7,7)));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock.png")));    
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        jTextField1.setBorder(new CompoundBorder(new LineBorder(new Color(0,0,0), 2),new EmptyBorder(7,7,7,7)));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock (1).png")));    
    }//GEN-LAST:event_jTextField1FocusLost

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.out.println(o);
        if(o>=10){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new setup().setVisible(true);
                }
            });
            this.dispose();
        }else{
            o++;
            Thread th=new Thread(){
               public void run(){
                    try{
                        Thread.sleep(5000);
                        o=0;
                    }catch(Exception e){}
                }
            };th.start();
            
        }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
class RoundedPanel extends JPanel
{
    private Color backgroundColor;
    private int cornerRadius = 15;
    public RoundedPanel(LayoutManager layout, int radius) {
    super(layout);
    cornerRadius = radius;
    }
    public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
    super(layout);
    cornerRadius = radius;
    backgroundColor = bgColor;
    }
    public RoundedPanel(int radius) {
    super();
    cornerRadius = radius;
    }
    public RoundedPanel(int radius, Color bgColor) {
    super();
    cornerRadius = radius;
    backgroundColor = bgColor;
    }

    @Override
    protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    Dimension arcs = new Dimension(cornerRadius, cornerRadius);
    int width = getWidth();
    int height = getHeight();
    Graphics2D graphics = (Graphics2D) g;
    graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
    RenderingHints.VALUE_ANTIALIAS_ON);
    //Draws the rounded panel with borders.
    if (backgroundColor != null) {
    graphics.setColor(backgroundColor);
    } else {
    graphics.setColor(getBackground());
    }

    graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paintbackground
    graphics.setColor(getForeground());
     //graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paintborder

        }
}
   
    
    
}
