/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trouvaille_destiano;
import Frames.Login;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Computer 1
 */
public class setup extends javax.swing.JFrame {

    /**
     * Creates new form setup
     */
    public setup() {
        initComponents();
        jLabel2.setVisible(false);
        jButton1.setVisible(false);
        try{
            Class.forName("java.sql.Driver");
            Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Trouvaille_Destiano","root","root");
            Statement stmt=cn.createStatement();   
            stmt.executeUpdate("show tables");
            jButton1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel2.setText("Already available");
            
        }catch(Exception e){ 
            try{
                Class.forName("java.sql.Driver");            
                Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/?","root","root");
                Statement stmt=cn.createStatement();   
                stmt.executeUpdate("create database Trouvaille_Destiano");
                cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Trouvaille_Destiano","root","root");
                stmt=cn.createStatement();
                stmt.executeUpdate("Use Trouvaille_Destiano");
                stmt.executeUpdate("create table admin(user_id varchar(30) Primary key, password varchar(30) not null,"
                        + "support_admin varchar(30), name varchar(40), p_no varchar(20), dob varchar(20), gender int(1));");
                stmt.executeUpdate("create table user(slno int(6) Unique, user_id varchar(30) Primary key, password varchar(30) not null,"
                        + "recovery_code varchar(30), name varchar(40), p_no varchar(20), email varchar(60), dob varchar(20), gender int(1));");
                stmt.executeUpdate("insert into user values(1,'', '', 1, '', '', '', '', 1)");
                stmt.executeUpdate("insert into admin values('32(1).160(5).96(3).', '-112(7).-16(1).-80(5).', '', '', '', '', 1)");
                stmt.executeUpdate("create table train(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                stmt.executeUpdate("create table flight(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                stmt.executeUpdate("insert into flight values(1,111111,'','',0,'')");
                stmt.executeUpdate("insert into train values(1,111111,'','',0,'')");
                stmt.executeUpdate("create table nowtrain(sno int(1),now varchar(40))");
                stmt.executeUpdate("create table suggestion(station varchar(45) unique)");
                stmt.executeUpdate("create table flightsuggestion(station varchar(45) unique)");
                stmt.executeUpdate("create table tourpackage(title varchar(30),price int(6), contact varchar(40), image longblob)");                
                jLabel2.setVisible(true);
                jLabel4.setVisible(true);
                jLabel3.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jButton1.setVisible(true);
                jButton1.setText("Done");
                
            }catch(Exception ex){
                System.out.println(ex);                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Setting Database..............");

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Created!!");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Recreate");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new Color(255,255,255), new java.awt.Color(153, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("aaa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First admin ID : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First admin Password : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("111");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().equals("Done")){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Login().setVisible(true);
                }
            }); 
            this.dispose();
        }else{
            try{
                Class.forName("java.sql.Driver");
                Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Trouvaille_Destiano","root","root");
                Statement stmt=cn.createStatement();   
                stmt.executeUpdate("show tables");
                stmt.executeUpdate("drop database Trouvaille_Destiano");
                stmt.executeUpdate("create database Trouvaille_Destiano");
                cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Trouvaille_Destiano","root","root");
                stmt=cn.createStatement();
                stmt.executeUpdate("Use Trouvaille_Destiano");
                stmt.executeUpdate("create table admin(user_id varchar(30) Primary key, password varchar(30) not null,"
                            + "support_admin varchar(30), name varchar(40), p_no varchar(20), dob varchar(20), gender int(1));");
                stmt.executeUpdate("create table user(slno int(6) Unique, user_id varchar(30) Primary key, password varchar(30) not null,"
                            + "recovery_code varchar(30), name varchar(40), p_no varchar(20), email varchar(60), dob varchar(20), gender int(1));");
                stmt.executeUpdate("insert into user values(1,'', '', 1, '', '', '', '', 1)");
                stmt.executeUpdate("insert into admin values('32(1).160(5).96(3).', '-112(7).-16(1).-80(5).', '', '', '', '', 1)");
                stmt.executeUpdate("create table train(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                stmt.executeUpdate("create table flight(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                stmt.executeUpdate("insert into flight values(1,111111,'','',0,'')");
                stmt.executeUpdate("insert into train values(1,111111,'','',0,'')");
                stmt.executeUpdate("create table nowtrain(sno int(1),now varchar(40))");
                stmt.executeUpdate("create table suggestion(station varchar(45) unique)");
                stmt.executeUpdate("create table flightsuggestion(station varchar(45) unique)");
                stmt.executeUpdate("create table tourpackage(title varchar(30),price int(6), contact varchar(40), image longblob)");
                jLabel4.setVisible(true);
                jLabel3.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel2.setText("Created");
                jButton1.setText("Done");           
            }catch(Exception e){ 
                try{
                    Class.forName("java.sql.Driver");            
                    Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/?","root","root");
                    Statement stmt=cn.createStatement();   
                    stmt.executeUpdate("create database Trouvaille_Destiano");
                    cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Trouvaille_Destiano","root","root");
                    stmt=cn.createStatement();
                    stmt.executeUpdate("Use Trouvaille_Destiano");
                    stmt.executeUpdate("create table admin(user_id varchar(30) Primary key, password varchar(30) not null,"
                            + "support_admin varchar(30), name varchar(40), p_no varchar(20), dob varchar(20), gender int(1));");
                    stmt.executeUpdate("create table user(slno int(6) Unique, user_id varchar(30) Primary key, password varchar(30) not null,"
                            + "recovery_code varchar(30), name varchar(40), p_no varchar(20), email varchar(60), dob varchar(20), gender int(1));");
                    stmt.executeUpdate("insert into user values(1,'', '', 1, '', '', '', '', 1)");
                    stmt.executeUpdate("insert into admin values('32(1).160(5).96(3).', '-112(7).-16(1).-80(5).', '', '', '', '', 1)");
                    stmt.executeUpdate("create table train(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                    stmt.executeUpdate("create table flight(slno int(10), number int(11), name varchar(45), days varchar(35), available int(1), rate varchar(100))");
                    stmt.executeUpdate("insert into flight values(1,111111,'','',0,'')");
                    stmt.executeUpdate("insert into train values(1,111111,'','',0,'')");
                    stmt.executeUpdate("create table nowtrain(sno int(1),now varchar(40))");
                    stmt.executeUpdate("create table suggestion(station varchar(45) unique)");
                    stmt.executeUpdate("create table flightsuggestion(station varchar(45) unique)");
                    stmt.executeUpdate("create table tourpackage(title varchar(30),price int(6), contact varchar(40), image longblob)");
                    jLabel4.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel2.setText("Created");
                    jButton1.setText("Done");                
                }catch(Exception ex){
                    System.out.println(ex);                
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
